-- Generated by scripts/generate-seed-sql.mjs — do not edit by hand.
-- Run supabase/schema.sql first, then paste this into the Supabase SQL editor.

insert into public.services (slug, title, copy, image, icon, points, sort_order, published) values
  ('corporate-events', 'Corporate Events', 'Organized at star banquets to brief employees on future strategies, facilitate discussions, and encourage the exchange of ideas and opinions.', '/media/s1.jpg', 'Building2', array['Annual conferences, townhalls and dealer meets', 'Award nights, gala dinners and celebrations', 'Stage design, production and AV management', 'Guest management, hospitality and logistics']::text[], 1, true),
  ('festival-activation', 'Festival Activation', 'Our team works closely with you to bring your vision to life, ensuring every detail reflects your unique style, personality and preferences.', '/media/s2.jpg', 'Sparkles', array['Durga Puja and festive property activations', 'Pandal branding and experience zones', 'Cultural performances and crowd engagement', 'Permissions, vendor and crowd-flow management']::text[], 2, true),
  ('exhibition', 'Exhibition', 'From venue selection and creative booth design to pre-event marketing, staff training and on-ground execution — every detail handled.', '/media/s3.jpg', 'LayoutPanelTop', array['Creative booth design and fabrication', 'Venue selection and space negotiation', 'Pre-event marketing and visitor drives', 'Trained staffing and lead capture']::text[], 3, true),
  ('brand-activation', 'Brand Activation', 'From immersive experiences to strategic engagements, we help brands inspire audiences and turn interactions into lasting loyalty.', '/media/s4.jpg', 'Megaphone', array['Mall, retail and campus experiences', 'Sampling, demo and photo-op installations', 'Promoter recruitment and training', 'Reporting, imagery and campaign analytics']::text[], 4, true),
  ('roadshows', 'Roadshows & Activations', 'We bring brands to life through engaging activations, immersive experiences and seamless on-ground execution.', '/media/s5.jpg', 'Truck', array['Multi-city route planning and permissions', 'Mobile stages, LED trucks and canters', 'Anchors, artists and crowd engagement', 'Daily reporting across every city']::text[], 5, true),
  ('sports-csr', 'Sports / CSR Events', 'Venue selection, catering, games, return gifts and more — activities designed to enhance community spirit, teamwork and health.', '/media/s6.jpg', 'Trophy', array['Corporate sports days and tournaments', 'Marathons, walkathons and health drives', 'CSR and community outreach programmes', 'Catering, trophies and return gifts']::text[], 6, true),
  ('trade-activation', 'Trade Activation', 'Channel and retail programmes that move product — designed for distributors, dealers and the last mile of your market.', '/media/s7.jpg', 'Store', array['Dealer, distributor and channel partner meets', 'In-shop branding and retail visibility drives', 'Trade schemes, incentives and loyalty programmes', 'Market-wise execution and on-ground reporting']::text[], 7, true),
  ('special-assignment', 'Special Assignment', 'One-of-a-kind mandates that don''t fit a template — conceptualised, produced and delivered end to end by a dedicated team.', '/media/s8.jpg', 'Star', array['Bespoke concepts and custom production', 'Government, institutional and CSR mandates', 'Milestone celebrations and inaugurations', 'Dedicated project team from brief to closure']::text[], 8, true)
on conflict (slug) do update set title = excluded.title, copy = excluded.copy, image = excluded.image, icon = excluded.icon, points = excluded.points, sort_order = excluded.sort_order, updated_at = now();

insert into public.clients (name, logo, website, sort_order, published) values
  ('Pepsi', '/media/clients/pepsi-logo.png', null, 1, true),
  ('Nestlé', '/media/clients/nestle-logo.png', null, 2, true),
  ('ITC', '/media/clients/itc-logo.png', null, 3, true),
  ('Reliance', '/media/clients/reliance-logo.png', null, 4, true),
  ('HP', '/media/clients/hp-logo.png', null, 5, true),
  ('Nokia', '/media/clients/nokia-logo.png', null, 6, true),
  ('Kellogg''s', '/media/clients/kelloggs-logo.png', null, 7, true),
  ('Johnson & Johnson', '/media/clients/j-j.png', null, 8, true),
  ('ICICI Bank', '/media/clients/icici-bank.png', null, 9, true),
  ('HDFC', '/media/clients/hdfc-logo.png', null, 10, true),
  ('Airtel', '/media/clients/airtel-logo.png', null, 11, true),
  ('Vodafone', '/media/clients/vodafone-logo-08.png', null, 12, true),
  ('Emami', '/media/clients/emami-logo.png', null, 13, true),
  ('IPL', '/media/clients/ipl.png', null, 14, true),
  ('Star Sports', '/media/clients/star-sports.png', null, 15, true)
on conflict (name) do update set logo = excluded.logo, website = excluded.website, sort_order = excluded.sort_order;

insert into public.gallery_categories (slug, title, copy, sort_order, published) values
  ('corporate-events', 'Corporate Events', 'Conferences, annual days and townhalls at star banquets — staged, produced and run end to end.', 1, true),
  ('festival-activation', 'Festival Activation', 'Durga Puja and festive properties built around culture, craft and crowd flow.', 2, true),
  ('exhibition', 'Exhibition', 'Booth design, fabrication, staffing and on-ground execution for trade fairs and expos.', 3, true),
  ('brand-activation', 'Brand Activation', 'Mall, retail and campus experiences that turn footfall into conversation.', 4, true),
  ('roadshows', 'Roadshows & Activations', 'Multi-city mobile stages, anchors and crowd engagement, city after city.', 5, true),
  ('sports-csr', 'Sports & CSR Events', 'Sports days, marathons and community initiatives built for teamwork and impact.', 6, true)
on conflict (slug) do update set title = excluded.title, copy = excluded.copy, sort_order = excluded.sort_order;

delete from public.gallery_images;
insert into public.gallery_images (category_slug, url, caption, sort_order, published) values
  ('corporate-events', '/media/gallery/corp-1.jpg', 'Annual conference, Kolkata', 1, true),
  ('corporate-events', '/media/gallery/corp-2.jpg', 'Leadership townhall', 2, true),
  ('corporate-events', '/media/gallery/corp-3.jpg', 'Awards night main stage', 3, true),
  ('corporate-events', '/media/gallery/corp-4.jpg', 'Product launch keynote', 4, true),
  ('corporate-events', '/media/gallery/corp-5.jpg', 'Gala dinner setup', 5, true),
  ('corporate-events', '/media/gallery/corp-6.jpg', 'Panel discussion stage', 6, true),
  ('corporate-events', '/media/s1.jpg', 'Backstage production', 7, true),
  ('festival-activation', '/media/gallery/fest-1.jpg', 'Puja pandal activation', 1, true),
  ('festival-activation', '/media/gallery/fest-2.jpg', 'Festive brand zone', 2, true),
  ('festival-activation', '/media/gallery/fest-3.jpg', 'Cultural showcase', 3, true),
  ('festival-activation', '/media/gallery/fest-4.jpg', 'Illuminated festive gate', 4, true),
  ('festival-activation', '/media/gallery/fest-5.jpg', 'Dhunuchi performance', 5, true),
  ('festival-activation', '/media/gallery/fest-6.jpg', 'Festive retail counter', 6, true),
  ('festival-activation', '/media/s2.jpg', 'Evening festive crowd', 7, true),
  ('exhibition', '/media/gallery/exhib-1.jpg', 'Trade expo pavilion', 1, true),
  ('exhibition', '/media/gallery/exhib-2.jpg', 'Custom booth build', 2, true),
  ('exhibition', '/media/gallery/exhib-3.jpg', 'Product display wall', 3, true),
  ('exhibition', '/media/gallery/exhib-4.jpg', 'Double-decker stall', 4, true),
  ('exhibition', '/media/gallery/exhib-5.jpg', 'Interactive demo bay', 5, true),
  ('exhibition', '/media/gallery/exhib-6.jpg', 'Expo hall walkthrough', 6, true),
  ('exhibition', '/media/s3.jpg', 'Visitor engagement desk', 7, true),
  ('brand-activation', '/media/gallery/brand-1.jpg', 'Mall experience zone', 1, true),
  ('brand-activation', '/media/gallery/brand-2.jpg', 'Sampling counter', 2, true),
  ('brand-activation', '/media/gallery/brand-3.jpg', 'Interactive brand pod', 3, true),
  ('brand-activation', '/media/gallery/brand-4.jpg', 'Campus engagement drive', 4, true),
  ('brand-activation', '/media/gallery/brand-5.jpg', 'Photo-op installation', 5, true),
  ('brand-activation', '/media/gallery/brand-6.jpg', 'Retail launch takeover', 6, true),
  ('brand-activation', '/media/s4.jpg', 'Brand pop-up counter', 7, true),
  ('roadshows', '/media/gallery/road-1.jpg', 'Night roadshow stage', 1, true),
  ('roadshows', '/media/gallery/road-2.jpg', 'Mobile activation van', 2, true),
  ('roadshows', '/media/gallery/road-3.jpg', 'On-ground engagement', 3, true),
  ('roadshows', '/media/gallery/road-4.jpg', 'LED truck rollout', 4, true),
  ('roadshows', '/media/gallery/road-5.jpg', 'Anchor crowd interaction', 5, true),
  ('roadshows', '/media/gallery/road-6.jpg', 'City square setup', 6, true),
  ('roadshows', '/media/s5.jpg', 'Convoy on the move', 7, true),
  ('sports-csr', '/media/gallery/sport-1.jpg', 'Corporate sports day', 1, true),
  ('sports-csr', '/media/gallery/sport-2.jpg', 'Community CSR drive', 2, true),
  ('sports-csr', '/media/gallery/sport-3.jpg', 'Team engagement', 3, true),
  ('sports-csr', '/media/gallery/sport-4.jpg', 'Marathon flag-off', 4, true),
  ('sports-csr', '/media/gallery/sport-5.jpg', 'Tug of war finals', 5, true),
  ('sports-csr', '/media/gallery/sport-6.jpg', 'Trophy presentation', 6, true),
  ('sports-csr', '/media/s6.jpg', 'Community celebration', 7, true);

delete from public.testimonials;
insert into public.testimonials (quote, name, org, sort_order, published) values
  ('They took a two-line brief and returned a full experience. Our annual conference in Kolkata has never run this smoothly.', 'Regional Marketing Head', 'FMCG Major', 1, true),
  ('Three cities, nine days of roadshows, zero surprises. The on-ground team is calm, sharp and completely dependable.', 'Brand Manager', 'Telecom Brand', 2, true),
  ('The exhibition booth pulled the highest footfall we''ve had. Design, build and staffing were all handled end to end.', 'AVP Communications', 'Private Bank', 3, true);

insert into public.site_settings (key, value) values
  ('phone', '"9831085630"'::jsonb),
  ('email', '"niladdri@communicationevent.in"'::jsonb),
  ('address', '"Communication & Events, 335, Jodhpur Park, Kolkata 700068"'::jsonb),
  ('hero_video', '"/media/hero-loop.mp4"'::jsonb),
  ('hero_poster', '"/media/hero.jpg"'::jsonb),
  ('founder_image', '"/media/founder.jpg"'::jsonb),
  ('founder_name', '"Niladdri Biswas"'::jsonb),
  ('about_body', '["With over 3 decades of unparalleled proficiency in executing successful promotions, campaigns and events, our founder has a deep understanding of effectively engaging target audiences and creating memorable experiences that leave a lasting impact.","Whether it''s a large-scale product launch or an intimate brand activation, our founder''s expertise in logistics, marketing and event management ensures seamless execution and remarkable results. With a proven track record in executing mega events and working with international and national celebrities, he has successfully curated and promoted a diverse range of events, elevating the profiles of both established and up-and-coming artists.","Our team of professionals is driven by commitment, motivation and passion to produce memorable brand events. We have all the expertise under one roof to ensure the success of any activity."]'::jsonb),
  ('stats', '[{"value":100,"suffix":"+","label":"Brands Served"},{"value":1000,"suffix":"+","label":"Successful Events"},{"value":30,"suffix":"+","label":"Years of Excellence"}]'::jsonb)
on conflict (key) do update set value = excluded.value, updated_at = now();
